### ISSUE TITLE
Can't see the list of all notifications.

### ISSUE THREAD

**Issue by Insaneous** [Nepeta/Axon#5]
As the title says. I'm on iOS 11.3.1, Axon version 0.1.4.

https://streamable.com/4k9j5

**Comment by Insaneous** [comment]
Also just now this strange animation appeared.

https://streamable.com/qk98n

**Comment by Nepeta** [comment]
@Insaneous Could you confirm if the main issue still exists in 0.1.5-1?

As for animations: I can't do anything here.

**Comment by Insaneous** [comment]
Yes, and it's same on 0.1.5-2. Also saw people on Reddit with same request.

**Comment by Nepeta** [comment]
@Insaneous oh yeah, that's not something Axon has or will have, misunderstood your report.

**Comment by Insaneous** [comment]
Oh, well that's unfortunate :(
But still thanks for all your hard work.
